#!/bin/bash

if ! type cargo > /dev/null; then
  read -p "Cargo/Rust is not found on this system. Would you like to install? [Y/n] " install_rust
  if [[ "${install_rust}" == "Y" ]]; then
    curl https://sh.rustup.rs -sSf | sh
    source $HOME/.cargo/env
  fi
fi

pck=$(command -v pyo3-pack)

if [[ "${pck}" == "" ]]; then
  read -p "PY03-Pack not found. Install PY03-Pack? [Y/n] " pyo
  if [[ "${pyo}" == "Y" ]]; then
    pip install pyo3-pack
  fi
fi

pyo3-pack build

echo -e "\n"
read -p "Hedera SDK Built Successfully. Install Hedera SDK? [Y/n] " install

if [[ "${install}" != "Y" ]]; then
  exit
fi

declare -a build_files

count=0
echo -e "\nBuild Files\n"
for entry in ./target/wheels/*
do
  echo "[${count}] $entry"
  build_files[count]=$entry
  count=$((count+1))
done

read -p "Select Build File To Install: " index
echo -e "\n"

echo "Selected: ${build_files[$index]}"

echo "Installing..."
pip install --force-reinstall ${build_files[$index]}
